#!/bin/bash
set -e

DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo ""
echo "╔══════════════════════════════════════╗"
echo "║        dotfiles setup starting       ║"
echo "╚══════════════════════════════════════╝"
echo ""

bash "$DOTFILES_DIR/scripts/brew.sh"
echo ""
bash "$DOTFILES_DIR/scripts/shell.sh"
echo ""
bash "$DOTFILES_DIR/scripts/node.sh"
echo ""

echo "==> Android SDK setup requires two manual steps before continuing."
echo ""
echo "    Step 1: Open Android Studio and complete the setup wizard"
echo "            (this downloads the Android SDK)"
echo ""
echo "    Step 2: Install the Command-line Tools:"
echo "            Settings > Languages & Frameworks > Android SDK"
echo "            > SDK Tools tab > check 'Android SDK Command-line Tools (latest)'"
echo "            > Apply"
echo ""
echo "    These steps are required for sdkmanager to be available."
echo ""
read -rp "    Press Enter when both steps are done..." _ </dev/tty
echo ""
bash "$DOTFILES_DIR/scripts/android.sh"
echo ""
bash "$DOTFILES_DIR/scripts/iterm.sh"
echo ""

echo "╔══════════════════════════════════════╗"
echo "║         setup complete!              ║"
echo "╚══════════════════════════════════════╝"
echo ""
echo "Next steps:"
echo "  1. Restart iTerm2 — go to Preferences > Profiles and set 'Catppuccin Macchiato' as default"
echo "  2. Open a new terminal session for zsh changes to take effect"
echo "  3. Launch Android Studio once to finish initial SDK setup (if first install)"
